const mongoose=require('mongoose')
const ProductSchema= mongoose.Schema({
    date:{
        type:String,
        required:true
    },
    code_no:{
        type:String,
        required:true
    },
    gross_weight:{
        type:String,
        required:true
    },
   less_vax:{
        type:String,
        required:true,
    },
    less_manimoti:
    {
        type:String,
        required:true
    },
   less_others_sil:{
        type:String,
        required:true
    },
    ghat_weight:
    {
        type:String,
        required:true
    },
    kundan_weight:
    {
        type:String,
        required:true
    },
   net_weight:{
        type:String,
        required:true
    },
   pcs_k:{
        type:String,
        required:true
    },
    tak_pcs:{
        type:String,
        required:true
    },
   extra:{
        type:String,
        required:true
    },
    Sil_victo:{
        type:String,
        required:true
    },
    total:{
        type:String,
        required:true
    },
},{timestamps:true})
const Product=mongoose.model('PRODUCT',ProductSchema)
module.exports=Product